#!/bin/sh /etc/rc.common

START=99
STOP=99

LAN_LED_PATH="/sys/class/leds/alfa:yellow:lan/brightness"
WLAN_LED_PATH="/sys/class/leds/alfa:yellow:wlan/brightness"
SYS_LED_PATH="/sys/class/leds/alfa:yellow:sys/brightness"

start() {
    echo "starting netaidkit."
}

stop() {
    echo "stopping netaidkit."
}

boot() {
    # Clear LEDS
    echo "0" > $LAN_LED_PATH
    echo "0" > $WLAN_LED_PATH
	echo "0" > $SYS_LED_PATH

    # Start nakd
    (/usr/bin/nakd &>/dev/null) &

    # Set domain socket permissions
    chgrp www-data /run/nakd
    chmod g+w /run/nakd

    # Check if uplink SSID is still in range.
    ssid_conf=$(uci -q show wireless.@wifi-iface[0].ssid | grep -o "'.*'")

    if [ -n "$ssid_conf" ]; then
        ssid=${ssid_conf:1:$((${#ssid_conf} - 2))}

        in_range=$(/usr/bin/iwinfo wlan0 scan | grep "$ssid")
        if [ -n "$in_range" ]; then
            uci set wireless.@wifi-iface[0].disabled=0
            uci commit
            wifi
        else
            uci set wireless.@wifi-iface[0].disabled=1
            uci commit
            wifi
        fi
    fi


    # Reboot daemons for state persistence.
    stage=$(cat /etc/stage)
    if [ $stage = "3" ]; then
        echo "1" > $LAN_LED_PATH
        rm /var/log/tor/notices.log
        /etc/init.d/tor start
    elif [ $stage = "4" ]; then
        echo "1" > $LAN_LED_PATH
        > /var/log/openvpn.log
        openvpn --log-append /var/log/openvpn.log --daemon --config /nak/ovpn/current.ovpn
    else
        echo "1" > $WLAN_LED_PATH
    fi
}
